/* ============================================================================
   VIDEOS.JS — SINGLE SOURCE OF TRUTH   ·   generated by the Video Manager
   ----------------------------------------------------------------------------
   Each entry is a VIDEO or an IMAGE/GIF.
     • VIDEO   : plays in the lightbox. Add  bunny: "<embed-url>"  for a Bunny
                 Stream player, or drop a local videos/<cat>/<file>.mp4.
                 Poster comes from  videos/<cat>/<file>.jpg  (optional).
     • IMAGE   : add  src: "<file>.(gif|png|jpg|webp)"  — shown as-is.
     • autoplay: true  → loops muted right in the card (compilations).
   cat ∈ entertainment | educational | corporate | showreel
   Flip MEDIA_READY to true once local posters/mp4s exist. Bunny videos always play.
   ============================================================================ */

const VIDEOS = [
  { cat: "entertainment", file: "ent_1", title: "Brand teaser — fast-cut hook", client: "VRSS", instagram: "https://www.instagram.com/vrss_fightgear/" },
  { cat: "entertainment", file: "ent_2", title: "Highlight reel — match night", client: "VRSS", instagram: "", autoplay: true },
  { cat: "entertainment", file: "ent_3", title: "Behind the scenes", client: "Studio Form", instagram: "" },
  { cat: "entertainment", file: "ent_4", title: "Trend remix (GIF)", client: "Creator", instagram: "", src: "ent_4.gif" },
  { cat: "educational", file: "edu_1", title: "How-to short — technique #3", client: "VRSS", instagram: "" },
  { cat: "educational", file: "edu_2", title: "Explainer — gear breakdown", client: "VRSS", instagram: "" },
  { cat: "educational", file: "edu_3", title: "Tutorial — 3 quick tips", client: "Studio Form", instagram: "" },
  { cat: "educational", file: "edu_4", title: "Stat card (image)", client: "Creator", instagram: "", src: "edu_4.png" },
  { cat: "corporate", file: "cor_1", title: "Product launch film", client: "VRSS", instagram: "" },
  { cat: "corporate", file: "cor_2", title: "Founder story", client: "VRSS", instagram: "" },
  { cat: "corporate", file: "cor_3", title: "Event recap", client: "Studio Form", instagram: "" },
  { cat: "showreel", file: "reel_main", title: "Showreel 2026", client: "Jassem", instagram: "" },
  { cat: "showreel", file: "vsl_1", title: "Brand VSL — full edit", client: "VRSS", instagram: "" },
];

/* HIGHLIGHTED WORK — bento: 1 big 16:9 + up to 5 verticals (first 2 top-right, next 3 bottom). */
const FEATURED_LAYOUT = {
  bigCard: "vsl_1",
  verticalCards: ["ent_1", "edu_1", "cor_1", "ent_2", "cor_2"],
};

/* CASE STUDIES — ordered file ids per section (data-case="<key>" in index.html).
   Tokens may force orientation: "id:h" (horizontal) or "id:v". */
const CASE_STUDIES = {
  vrss: ["edu_2", "ent_1", "cor_2"],
  alex: ["ent_1", "ent_2", "ent_3", "ent_4", "edu_1", "edu_2", "edu_3", "edu_4"],
  scm: ["vsl_1:h", "ent_4:v", "cor_3"],
};
const VRSS_VIDEOS = CASE_STUDIES.vrss; // legacy alias

/* HERO MEDIA — relative to videos/. Image ext → still; video ext → player. */
const HERO_MEDIA = "showreel/img_main.png";

/* MEDIA READY — false keeps placeholder mode (no requests for missing local files). */
const MEDIA_READY = false;

window.PORTFOLIO_DATA = { VIDEOS, FEATURED_LAYOUT, CASE_STUDIES, VRSS_VIDEOS, HERO_MEDIA, MEDIA_READY };