/* ============================================================================
   APP.JSX — Video Manager. State, library, drawer wiring, export.
   ============================================================================ */
const { useState, useEffect, useMemo, useRef } = React;
const { CATS, CAT_LABEL, isImageSrc, cls } = window.AdminConst;
const { Ic, VideoCard, VideoEditor, MediaTest, FeaturedPanel, CasesPanel, HeroPanel } = window;

const DRAFT_KEY = "jassem_video_admin_v1";
const KNOWN_CLIENTS = ["VRSS", "Alex", "SCM", "Studio Form", "Creator", "Brand", "Jassem"];

/* ---------- load baseline from videos.js ---------- */
function readBaseline() {
  const D = window.PORTFOLIO_DATA || {};
  return {
    videos: (D.VIDEOS || []).map(v => ({
      cat: v.cat, file: v.file, title: v.title || "", client: v.client || "",
      instagram: v.instagram || "", bunny: v.bunny || "", src: v.src || "", customThumb: v.customThumb || "", autoplay: !!v.autoplay,
    })),
    featured: {
      bigCard: (D.FEATURED_LAYOUT || {}).bigCard || "",
      verticalCards: ((D.FEATURED_LAYOUT || {}).verticalCards || []).slice(),
    },
    cases: {
      vrss: ((D.CASE_STUDIES || {}).vrss || D.VRSS_VIDEOS || []).slice(),
      alex: ((D.CASE_STUDIES || {}).alex || []).slice(),
      scm: ((D.CASE_STUDIES || {}).scm || []).slice(),
    },
    hero: D.HERO_MEDIA || "",
    mediaReady: !!D.MEDIA_READY,
  };
}

/* ---------- serialize back to videos.js ---------- */
function serialize(s) {
  const q = x => JSON.stringify(x == null ? "" : x);
  const vlines = s.videos.map(v => {
    const p = [`cat: ${q(v.cat)}`, `file: ${q(v.file)}`, `title: ${q(v.title)}`, `client: ${q(v.client)}`, `instagram: ${q(v.instagram)}`];
    if (v.bunny) p.push(`bunny: ${q(v.bunny)}`);
    if (v.customThumb) p.push(`customThumb: ${q(v.customThumb)}`);
    if (v.src) p.push(`src: ${q(v.src)}`);
    if (v.autoplay) p.push(`autoplay: true`);
    return `  { ${p.join(", ")} },`;
  }).join("\n");

  const arr = a => "[" + a.map(q).join(", ") + "]";
  const caseLines = ["vrss", "alex", "scm"].map(k => `  ${k}: ${arr(s.cases[k] || [])},`).join("\n");

  return `/* ============================================================================
   VIDEOS.JS — SINGLE SOURCE OF TRUTH   ·   generated by the Video Manager
   ----------------------------------------------------------------------------
   Each entry is a VIDEO or an IMAGE/GIF.
     • VIDEO   : plays in the lightbox. Add  bunny: "<embed-url>"  for a Bunny
                 Stream player, or drop a local videos/<cat>/<file>.mp4.
                 Poster comes from  videos/<cat>/<file>.jpg  (optional).
     • IMAGE   : add  src: "<file>.(gif|png|jpg|webp)"  — shown as-is.
     • autoplay: true  → loops muted right in the card (compilations).
   cat ∈ entertainment | educational | corporate | showreel
   Flip MEDIA_READY to true once local posters/mp4s exist. Bunny videos always play.
   ============================================================================ */

const VIDEOS = [
${vlines}
];

/* HIGHLIGHTED WORK — bento: 1 big 16:9 + up to 5 verticals (first 2 top-right, next 3 bottom). */
const FEATURED_LAYOUT = {
  bigCard: ${q(s.featured.bigCard)},
  verticalCards: ${arr(s.featured.verticalCards || [])},
};

/* CASE STUDIES — ordered file ids per section (data-case="<key>" in index.html).
   Tokens may force orientation: "id:h" (horizontal) or "id:v". */
const CASE_STUDIES = {
${caseLines}
};
const VRSS_VIDEOS = CASE_STUDIES.vrss; // legacy alias

/* HERO MEDIA — relative to videos/. Image ext → still; video ext → player. */
const HERO_MEDIA = ${q(s.hero)};

/* MEDIA READY — false keeps placeholder mode (no requests for missing local files). */
const MEDIA_READY = ${s.mediaReady ? "true" : "false"};

window.PORTFOLIO_DATA = { VIDEOS, FEATURED_LAYOUT, CASE_STUDIES, VRSS_VIDEOS, HERO_MEDIA, MEDIA_READY };
`;
}

/* ---------- helpers ---------- */
function uniqueFile(base, taken) {
  let f = base, i = 2;
  while (taken.includes(f)) { f = `${base}_${i++}`; }
  return f;
}
function nextFileId(cat, videos) {
  const prefix = { entertainment: "ent", educational: "edu", corporate: "cor", showreel: "reel" }[cat] || "vid";
  const taken = videos.map(v => v.file);
  let i = 1; while (taken.includes(`${prefix}_${i}`)) i++;
  return `${prefix}_${i}`;
}

/* =====================================================================
   APP
   ===================================================================== */
function App() {
  const baseline = useRef(readBaseline());
  const [state, setState] = useState(() => {
    try { const d = localStorage.getItem(DRAFT_KEY); if (d) return JSON.parse(d); } catch (e) {}
    return readBaseline();
  });
  const [hasDraft, setHasDraft] = useState(() => {
    try { return !!localStorage.getItem(DRAFT_KEY); } catch (e) { return false; }
  });
  const [tab, setTab] = useState("library");
  const [editing, setEditing] = useState(null);   // { draft, thumb }
  const [thumbs, setThumbs] = useState({});         // file -> dataURL (session)
  const [test, setTest] = useState(null);
  const [showExport, setShowExport] = useState(false);
  const [toast, setToast] = useState(null);
  const [dirHandle, setDirHandle] = useState(null);

  const connectFolder = async () => {
    if (!window.showDirectoryPicker) {
      flash("Not supported in this browser (use Chrome/Edge)");
      return;
    }
    try {
      const handle = await window.showDirectoryPicker({ mode: "readwrite" });
      setDirHandle(handle);
      flash("Folder connected!");
    } catch (e) {
      console.log(e);
    }
  };

  /* filters */
  const [q, setQ] = useState("");
  const [catF, setCatF] = useState("all");
  const [clientF, setClientF] = useState("all");
  const [group, setGroup] = useState("none");

  /* drag */
  const [dragIdx, setDragIdx] = useState(null);
  const [overIdx, setOverIdx] = useState(null);

  /* persist */
  useEffect(() => {
    try { localStorage.setItem(DRAFT_KEY, JSON.stringify(state)); setHasDraft(true); } catch (e) {}
  }, [state]);

  const dirty = useMemo(() => JSON.stringify(state) !== JSON.stringify(baseline.current), [state]);

  const byFile = useMemo(() => Object.fromEntries(state.videos.map(v => [v.file, v])), [state.videos]);
  const clients = useMemo(() => {
    const set = new Set(KNOWN_CLIENTS);
    state.videos.forEach(v => v.client && set.add(v.client));
    return [...set];
  }, [state.videos]);

  const featuredRole = useMemo(() => {
    const m = {};
    if (state.featured.bigCard) m[state.featured.bigCard] = "big";
    (state.featured.verticalCards || []).forEach((f, i) => { if (!m[f]) m[f] = `v${i + 1}`; });
    return m;
  }, [state.featured]);

  const flash = msg => { setToast(msg); setTimeout(() => setToast(null), 1800); };

  /* ---- mutations ---- */
  const openNew = () => {
    const cat = catF !== "all" ? catF : "entertainment";
    setEditing({ draft: { cat, file: nextFileId(cat, state.videos), title: "", client: clientF !== "all" ? clientF : "", instagram: "", bunny: "", src: "", customThumb: "", autoplay: false, __isNew: true, __orig: null }, thumb: null });
  };
  const openEdit = (v) => setEditing({ draft: { ...v, __orig: v.file, __isNew: false }, thumb: thumbs[v.file] || null });

  const commit = () => {
    const d = { ...editing.draft }; const orig = d.__orig; const isNew = d.__isNew;
    delete d.__orig; delete d.__isNew;
    if (editing.thumb && d.file) setThumbs(t => ({ ...t, [d.file]: editing.thumb }));
    setState(s => {
      let videos = s.videos.slice();
      if (isNew) videos.push(d);
      else { const i = videos.findIndex(x => x.file === orig); if (i >= 0) videos[i] = d; }
      let featured = s.featured, cases = s.cases;
      if (!isNew && orig && orig !== d.file) {
        const ren = t => { const [id, o] = String(t).split(":"); return id === orig ? (o ? `${d.file}:${o}` : d.file) : t; };
        featured = { bigCard: s.featured.bigCard === orig ? d.file : s.featured.bigCard, verticalCards: (s.featured.verticalCards || []).map(ren) };
        cases = Object.fromEntries(Object.entries(s.cases).map(([k, l]) => [k, l.map(ren)]));
      }
      return { ...s, videos, featured, cases };
    });
    setEditing(null);
    flash(isNew ? "Video added" : "Saved");
  };

  const removeVideo = (file) => {
    if (!window.confirm("Delete this video? It will also be removed from Highlighted work and case studies.")) return;
    setState(s => ({
      ...s,
      videos: s.videos.filter(v => v.file !== file),
      featured: { bigCard: s.featured.bigCard === file ? "" : s.featured.bigCard, verticalCards: (s.featured.verticalCards || []).filter(t => t.split(":")[0] !== file) },
      cases: Object.fromEntries(Object.entries(s.cases).map(([k, l]) => [k, l.filter(t => t.split(":")[0] !== file)])),
    }));
    setEditing(null);
    flash("Deleted");
  };

  const duplicate = (file) => {
    setState(s => {
      const i = s.videos.findIndex(v => v.file === file); if (i < 0) return s;
      const src = s.videos[i];
      const copy = { ...src, file: uniqueFile(src.file + "_copy", s.videos.map(v => v.file)), title: src.title ? src.title + " (copy)" : "" };
      const videos = s.videos.slice(); videos.splice(i + 1, 0, copy);
      return { ...s, videos };
    });
    flash("Duplicated");
  };

  /* ---- filtering / grouping ---- */
  const filtered = useMemo(() => {
    const ql = q.trim().toLowerCase();
    return state.videos.filter(v =>
      (catF === "all" || v.cat === catF) &&
      (clientF === "all" || v.client === clientF) &&
      (!ql || (v.title || "").toLowerCase().includes(ql) || (v.file || "").toLowerCase().includes(ql) || (v.client || "").toLowerCase().includes(ql))
    );
  }, [state.videos, q, catF, clientF]);

  const reorderEnabled = group === "none" && catF === "all" && clientF === "all" && !q.trim();

  const dragProps = (v) => {
    const idx = state.videos.indexOf(v);
    return {
      enabled: reorderEnabled,
      dragging: dragIdx === idx,
      over: overIdx === idx && dragIdx !== idx,
      onDragStart: e => { setDragIdx(idx); e.dataTransfer.effectAllowed = "move"; },
      onDragOver: e => { e.preventDefault(); setOverIdx(idx); },
      onDrop: e => {
        e.preventDefault();
        if (dragIdx == null || dragIdx === idx) return;
        setState(s => { const vs = s.videos.slice(); const [m] = vs.splice(dragIdx, 1); vs.splice(idx, 0, m); return { ...s, videos: vs }; });
        setDragIdx(null); setOverIdx(null);
      },
      onDragEnd: () => { setDragIdx(null); setOverIdx(null); },
    };
  };

  const renderCard = (v) => (
    <VideoCard key={v.file} v={v} featuredRole={featuredRole[v.file]}
      onEdit={() => openEdit(v)} onDup={() => duplicate(v.file)} onDelete={() => removeVideo(v.file)}
      drag={dragProps(v)} />
  );

  const grouped = useMemo(() => {
    if (group === "none") return null;
    const key = group === "client" ? (v => v.client || "— no client —") : (v => CAT_LABEL[v.cat] || v.cat);
    const map = {};
    filtered.forEach(v => { const k = key(v); (map[k] = map[k] || []).push(v); });
    return Object.entries(map);
  }, [filtered, group]);

  /* ---- export ---- */
  const code = useMemo(() => serialize(state), [state]);
  const doDownload = async () => {
    if (dirHandle) {
      try {
        const fileHandle = await dirHandle.getFileHandle("videos.js", { create: true });
        const writable = await fileHandle.createWritable();
        await writable.write(code);
        await writable.close();
        flash("videos.js saved directly to folder!");
        return;
      } catch (e) {
        console.error(e);
        flash("Save failed. Try downloading instead.");
      }
    }
    const blob = new Blob([code], { type: "text/javascript" });
    const a = document.createElement("a"); a.href = URL.createObjectURL(blob); a.download = "videos.js";
    document.body.appendChild(a); a.click(); a.remove(); URL.revokeObjectURL(a.href);
    flash("videos.js downloaded");
  };
  const doCopy = async () => { try { await navigator.clipboard.writeText(code); flash("Copied to clipboard"); } catch (e) { flash("Copy failed — select & copy manually"); } };
  const revert = () => {
    if (!window.confirm("Discard all draft changes and reload the data from videos.js?")) return;
    try { localStorage.removeItem(DRAFT_KEY); } catch (e) {}
    setState(readBaseline()); setHasDraft(false); setThumbs({}); flash("Reverted to file");
  };

  const TABS = [
    { id: "library", label: "Library", count: state.videos.length },
    { id: "featured", label: "Highlighted work" },
    { id: "cases", label: "Case studies" },
    { id: "hero", label: "Hero & settings" },
  ];

  return (
    <div className="app">
      {/* top bar */}
      <header className="topbar">
        <div className="topbar__row">
          <div className="brand"><span className="brand__mark" /><div>Video Manager<small>Jassem · private backstage</small></div></div>
          <div className="topbar__spacer" />
          <div className="savestate">
            <span className={cls("dot", dirty && "dot--dirty")} />
            {dirty ? "Unsaved vs file · draft autosaved" : "In sync with file"}
          </div>
          <button className="btn btn--ghost btn--sm" onClick={connectFolder} style={{ color: dirHandle ? "var(--ok)" : "inherit" }}>
            {dirHandle ? "Folder Connected" : "Connect Folder"}
          </button>
          <button className="btn btn--ghost btn--sm" onClick={revert} disabled={!dirty && !hasDraft}>Revert</button>
          <button className="btn btn--primary btn--sm" onClick={() => setShowExport(true)}>{Ic.export} Export videos.js</button>
        </div>
        <nav className="tabs">
          {TABS.map(t => (
            <button key={t.id} className={cls("tab", tab === t.id && "is-active")} onClick={() => setTab(t.id)}>
              {t.label}{t.count != null && <span className="count">{t.count}</span>}
            </button>
          ))}
        </nav>
      </header>

      <main className="main">
        {hasDraft && dirty && (
          <div className="banner">
            <span>You're viewing an autosaved draft. Export when ready, then replace <code style={{ fontFamily: "var(--mono)" }}>videos.js</code> in the project.</span>
            <button className="btn btn--soft btn--sm" onClick={revert}>Discard draft</button>
          </div>
        )}

        {tab === "library" && (
          <React.Fragment>
            <div className="toolbar">
              <div className="search">{Ic.search}<input placeholder="Search title, id, client…" value={q} onChange={e => setQ(e.target.value)} /></div>
              <div className="chips">
                {["all", ...CATS].map(c => (
                  <button key={c} className={cls("chip", catF === c && "is-active")} onClick={() => setCatF(c)}>{c === "all" ? "All" : CAT_LABEL[c]}</button>
                ))}
              </div>
              <div className="field-inline">Client
                <select className="selectbox" value={clientF} onChange={e => setClientF(e.target.value)}>
                  <option value="all">All</option>
                  {clients.map(c => <option key={c} value={c}>{c}</option>)}
                </select>
              </div>
              <div className="field-inline">Group
                <select className="selectbox" value={group} onChange={e => setGroup(e.target.value)}>
                  <option value="none">None</option>
                  <option value="client">By client</option>
                  <option value="category">By category</option>
                </select>
              </div>
              <div style={{ flex: 1 }} />
              <button className="btn btn--primary btn--sm" onClick={openNew}>{Ic.plus} Add video</button>
            </div>

            {!reorderEnabled && group === "none" && (
              <div style={{ fontSize: ".76rem", color: "var(--faint)", margin: "-6px 2px 12px" }}>Clear search & filters to drag-reorder cards.</div>
            )}
            {reorderEnabled && state.videos.length > 0 && (
              <div style={{ fontSize: ".76rem", color: "var(--faint)", margin: "-6px 2px 12px" }}>Drag cards to set the gallery order.</div>
            )}

            {filtered.length === 0 ? (
              <div className="empty">No videos match. <button className="btn btn--soft btn--sm" onClick={openNew} style={{ marginLeft: 8 }}>{Ic.plus} Add one</button></div>
            ) : grouped ? (
              grouped.map(([name, list]) => (
                <div className="group" key={name}>
                  <div className="group__head"><h3>{name}</h3><span className="count" style={{ fontFamily: "var(--mono)", fontSize: ".66rem" }}>{list.length}</span><div className="group__rule" /></div>
                  <div className="vgrid">{list.map(renderCard)}</div>
                </div>
              ))
            ) : (
              <div className="vgrid">
                {filtered.map(renderCard)}
                <button className="addcard" onClick={openNew}>{Ic.plus}<span>Add video</span></button>
              </div>
            )}
          </React.Fragment>
        )}

        {tab === "featured" && (
          <FeaturedPanel featured={state.featured} videos={state.videos} byFile={byFile} onChange={f => setState(s => ({ ...s, featured: f }))} />
        )}
        {tab === "cases" && (
          <CasesPanel cases={state.cases} videos={state.videos} byFile={byFile} onChange={(k, l) => setState(s => ({ ...s, cases: { ...s.cases, [k]: l } }))} />
        )}
        {tab === "hero" && (
          <HeroPanel hero={state.hero} videos={state.videos} mediaReady={state.mediaReady}
            onChange={h => setState(s => ({ ...s, hero: h }))} onReady={b => setState(s => ({ ...s, mediaReady: b }))} />
        )}
      </main>

      {/* editor drawer */}
      {editing && (
        <VideoEditor
          draft={editing.draft}
          thumb={editing.thumb}
          clients={clients}
          allFiles={state.videos.map(v => ({ file: v.file, __orig: v.file }))}
          onThumb={url => setEditing(e => ({ ...e, thumb: url }))}
          onChange={patch => setEditing(e => ({ ...e, draft: { ...e.draft, ...patch } }))}
          onTest={url => setTest(url)}
          onClose={() => setEditing(null)}
          onDelete={() => removeVideo(editing.draft.file)}
          onDup={() => { duplicate(editing.draft.file); setEditing(null); }}
          onSave={commit}
          dirHandle={dirHandle}
          flash={flash}
        />
      )}

      {test && <MediaTest url={test} onClose={() => setTest(null)} />}

      {/* export modal */}
      {showExport && (
        <div className="mscrim" onClick={() => setShowExport(false)}>
          <div className="exp" onClick={e => e.stopPropagation()}>
            <div className="exp__head"><h2>Export videos.js</h2><div style={{ flex: 1 }} /><button className="closex" onClick={() => setShowExport(false)}>{Ic.x}</button></div>
            <pre>{code}</pre>
            <div className="exp__steps">
              <b>To go live:</b> download (or copy) this file → replace <code>videos.js</code> at the project root → reload the site. Thumbnails dropped in the editor must be saved into their <code>videos/&lt;cat&gt;/</code> folders separately.
            </div>
            <div className="exp__foot">
              <button className="btn btn--soft" onClick={doCopy}>{Ic.copy} Copy</button>
              <div style={{ flex: 1 }} />
              <button className="btn btn--primary" onClick={doDownload}>{Ic.download} Download videos.js</button>
            </div>
          </div>
        </div>
      )}

      {toast && <div className="toast">{toast}</div>}
    </div>
  );
}

ReactDOM.createRoot(document.getElementById("root")).render(<App />);
